<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.7/dist/tailwind.min.css">
    <title>Lista de Tareas</title>
</head>
<?php

?>

<body class="bg-gray-100 flex items-center justify-center flex-col mc-auto ">
<div class="text-4xl mb-8 mt-10 text-center">PANEL DE TAREAS</div>

<div class="bg-gray-100 flex items-center justify-center flex-col">
    <form action="insertTask" method="post">
        <table class="w-full border-collapse border border-blue-200">
            <tr class="bg-gray-100">            
                <th class="py-2 px-4">Nº Tarea</th>
                <th class="py-2 px-4">Usuario</th>
                <th class="py-2 px-4">Tarea</th>
                <th class="py-2 px-4">Tipo de Tarea</th>
                <th class="py-2 px-4">Fecha de Creación</th>
                <th class="py-2 px-4">Fecha Fin Prevista</th>
                <th class="py-2 px-4">Estado de la tarea</th>
                <th class="py-2 px-4"></th>
                <th class="py-2 px-4"></th>
            </tr>

            <!-- Filas de inserción de datos -->
            <tr>
                <td></td>
                <td><input type='text' name='user' class='px-4 py-2 border border-blue-200 rounded'></td>
                <td><input type='text' name='taskName' class='px-4 py-2 border border-blue-200 rounded'></td>
                <td>
                    <select name="taskType" id="taskType" class='px-4 py-2 border border-blue-200 rounded'>
                        <option value="FrontEnd">FrontEnd</option>
                        <option value="BackEnd">BackEnd</option>
                        <option value="DataScience">Data Science</option>
                    </select>
                </td>
                <td><input type='text' name='creationDate' class='px-4 py-2 border border-blue-200 rounded'></td>
                <td><input type='text' name='expectedEndDate' class='px-4 py-2 border border-blue-200 rounded'></td>
                <td>
                    <select name="statusTask" id="statusTask" class='px-4 py-2 border border-blue-200 rounded'>
                        <option value="En ejecucion">En ejecucion</option>
                        <option value="Pendiente">Pendiente</option>
                        <option value="Finalizada">Finalizada</option>
                    </select>
                </td>
                <td class='py-2 px-4'><input type='submit' name='cr' id='cr' value='Insertar' class='bg-blue-200 text-white px-4 py-2 rounded hover:bg-blue-300'></td>
            </tr>

            <?php 
            $TaskController = new TaskController();
            $arrayTasks = $TaskController->tasksList_ViewAction();

            foreach($arrayTasks as $task): ?>
                <tr>
                <td class="text-center"><?php echo $task['taskId']?></td>
                <td class="text-center"><?php echo $task['user']?></td>
                <td class="text-center"><?php echo $task['taskName']?></td>
                <td class="text-center"><?php echo $task['taskType']?></td>
                <td class="text-center"><?php echo $task['creationDate']?></td>
                <td class="text-center"><?php echo $task['expectedEndDate']?></td>
                <td class="text-center"><?php echo $task['taskStatus']?></td>
                    <td class="py-2 px-4">
                        <a href="deleteTask?taskId=<?php echo $task['taskId']?>" onclick="return confirmDelete(<?php echo $task['taskId']?>);">
                            <input type='button' name='del' id='del' value='Borrar' class='bg-red-500 text-white px-4 py-2 rounded hover:bg-red-300'>
                        </a>
                    </td>
                    <td class='py-2 px-4 text-center'>
                        <a href="editTask?taskId=<?php echo $task['taskId']?> & user=<?php echo $task['user']?> & taskName=<?php echo $task['taskName']?> & taskType=<?php echo $task['taskType']?> & creationDate=<?php echo $task['creationDate']?> & expectedEndDate=<?php echo $task['expectedEndDate']?> & taskStatus=<?php echo $task['taskStatus']?>">
                            <input type='button' name='up' id='up' value='Actualizar' class='bg-green-500 text-white px-4 py-2 rounded'>
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
    </form>
</div>

<!-- Ventana emergente para confirmar borrado de registro -->
<script>
function confirmDelete(id) {
    return confirm("¿Estás seguro de que deseas borrar la tarea número: " + id + "?");
}
</script>

</body>
</html>