<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.7/dist/tailwind.min.css">
    <title>Lista de Tareas</title>
</head>

<body class="bg-gray-100 flex items-center justify-center flex-col mc-auto ">
    <div class="flex mt-6 mr-auto ml-7">
        <?php

        $user = $_SESSION['user'];

        echo "<p class='text-left text-4xl text-black'>Hola $user, bienvenid@!!</p>"
        ?>
    </div>

    <div class="flex mt-1 mr-4 ml-auto">
        <a href="close-user-session" class=" bg-blue-300 text-white px-4 py-2 rounded hover:bg-blue-500 mr-5 ">
            Cerrar sessión
        </a>
        <a href="user-profile_view" class="bg-blue-300 text-white px-4 py-2 rounded hover:bg-blue-500">
            Portal del Usuario
        </a>
    </div>

    <div class="text-6xl font-bold text-black mb-8 mt-10 text-center">PANEL DE TAREAS</div>

    <!-- Filas de titulos de columnas -->

    <form action="insert-task" method="post">
        <table class="w-full border-collapse border border-blue-200">
            <tr class="bg-gray-100">
                <th class="py-2 px-4">Usuario</th>
                <th class="py-2 px-4">Tarea</th>
                <th class="py-2 px-4">Tipo de Tarea</th>
                <th class="py-2 px-4">Fecha de Creación</th>
                <th class="py-2 px-4">Fecha Fin Prevista</th>
                <th class="py-2 px-4">Estado de la tarea</th>
                <th class="py-2 px-4"></th>
                <th class="py-2 px-4"></th>
            </tr>
            <tr class="bg-gray-100">

                <!-- Filas de filtrar datos -->
                <td>
                    <div class="flex items-center">
                        <a href="#" onclick="filterByUser()" title="Filtrar" class="mr-2">
                            <img src="../web/images/filtrar.png" alt="Icono de filtro" class="w-5 h-5">
                        </a>
                        <input type='text' id='filteredUser' class='px-0.5 py-2 border border-blue-200 rounded'>
                    </div>
                </td>
                <td>
                    <div class="flex items-center">
                        <a href="#" onclick="filterByTaskName()" title="Filtrar" class="mr-2">
                            <img src="../web/images/filtrar.png" alt="Icono de filtro" class="w-5 h-5">
                        </a>
                        <input type='text' id='filteredTaskName' class='px-0.5 py-2 border border-blue-200 rounded'>
                    </div>
                </td>
                <td class="flex items-center">
                    <a href="#" onclick="filterByTaskType()" class="mr-2">
                        <img src="../web/images/filtrar.png" alt="Icono de filtro" class="w-5 h-5">
                    </a>
                    <select name="filteredTaskType" id="filteredTaskType" class='px-4 py-2 border border-blue-200 rounded'>
                        <option value="--">--Escoje un valor--</option>
                        <option value="FrontEnd">FrontEnd</option>
                        <option value="BackEnd">BackEnd</option>
                        <option value="DataScience">Data Science</option>
                    </select>
                </td>
                <td></td>
                <td></td>
                <td></td>
            </tr>

            <!-- Filas de inserción de datos -->
            <tr>
                <td><input type='text' name='user' class='px-4 py-2 border border-blue-200 rounded text-center' value="<?php echo $user?>" readonly></td>
                <td><input type='text' name='taskName' class='px-4 py-2 border border-blue-200 rounded'></td>
                <td>
                    <select name="taskType" id="taskType" class='w-full px-4 py-2 border border-blue-200 rounded'>
                        <option value="--">--Escoje un valor--</option>
                        <option value="FrontEnd">FrontEnd</option>
                        <option value="BackEnd">BackEnd</option>
                        <option value="DataScience">Data Science</option>
                    </select>
                </td>
                <td><input type='date' name='creationDate' class='px-4 py-2 border border-blue-200 rounded'></td>
                <td><input type='date' name='expectedEndDate' class='px-4 py-2 border border-blue-200 rounded'></td>
                <td>
                    <select name="statusTask" id="statusTask" class='px-4 py-2 border border-blue-200 rounded'>
                        <option value="--">--Escoje un valor--</option>
                        <option value="En ejecucion">En ejecucion</option>
                        <option value="Pendiente">Pendiente</option>
                        <option value="Finalizada">Finalizada</option>
                    </select>
                </td>
                <td class='py-2 px-4'><input type='submit' name='cr' id='cr' value='Insertar' class='bg-blue-200 text-white px-7 py-2 rounded hover:bg-blue-300'></td>
            </tr>
            <!-- Listado tareas ya creadas -->
            <?php
            $TaskController = new TaskController();
            $arrayTasks = $TaskController->tasksList_ViewAction();
            if ($arrayTasks !== null) :
                foreach ($arrayTasks as $task) : ?>
                    <tr>
                        <td class="text-center"><?php echo $task['user'] ?></td>
                        <td class="text-center"><?php echo $task['taskName'] ?></td>
                        <td class="text-center"><?php echo $task['taskType'] ?></td>
                        <td class="text-center"><?php echo $task['creationDate'] ?></td>
                        <td class="text-center"><?php echo $task['expectedEndDate'] ?></td>
                        <td class="text-center"><?php echo $task['taskStatus'] ?></td>
                        <!-- boton borrar -->   
                        <td class="py-2 px-4">
                            <a href="delete-task?taskId=<?php echo $task['taskId'] ?>&taskName=<?php echo $task['taskName'] ?>" onclick="return confirmDelete('<?php echo $task['taskName'] ?>');">
                                <input type='button' name='del' id='del' value='Borrar' class='bg-red-500 text-white px-8 py-2 rounded hover:bg-red-300'>
                            </a>
                        </td>
                        <!-- boton actualizar -->
                        <td class='py-2 px-4 text-center'>
                            <a href="update-task_View?taskId=<?php echo $task['taskId'] ?> & user=<?php echo $task['user'] ?> & taskName=<?php echo $task['taskName'] ?> & taskType=<?php echo $task['taskType'] ?> & creationDate=<?php echo $task['creationDate'] ?> & expectedEndDate=<?php echo $task['expectedEndDate'] ?> & taskStatus=<?php echo $task['taskStatus'] ?>">
                                <input type='button' name='up' id='up' value='Actualizar' class='bg-green-500 text-white px-4 py-2 rounded hover:bg-green-300'>
                            </a>
                        </td>
                    </tr>
            <?php endforeach;
            endif; ?>
        </table>

       
    </form>
    <a href="list_view" class="bg-blue-300 text-white px-4 py-2 rounded hover:bg-blue-500 mt-5">
            Gestiona tus listas
        </a>
    </div>

    <!-- Ventana emergente para confirmar borrado de registro -->
    <script>
        function confirmDelete(taskname) {
            return confirm("¿Estás seguro de que deseas borrar la tarea: " + taskname + "?");
        }

        function filterByUser() {
            let filteredUser = document.getElementById("filteredUser").value;

            if (filteredUser != "") {
                window.location.href = "filter-by-user_view?filteredUser=" + filteredUser;
            } else {
                alert("Para filtrar debes introducir algun dato!");
            }
        }

        function filterByTaskName() {
            let filteredTaskName = document.getElementById("filteredTaskName").value;

            if (filteredTaskName != "") {
                window.location.href = "filter-by-task-name_view?filteredTaskName=" + filteredTaskName;
            } else {
                alert("Para filtrar debes introducir algun dato!");
            }
        }

        function filterByTaskType() {
            let filteredTaskType = document.getElementById("filteredTaskType").value;

            if (filteredTaskType != "--") {
                window.location.href = "filter-by-task-type_view?filteredTaskType=" + filteredTaskType;
            } else {
                alert("Para filtrar debes introducir algun dato!");
            }
        }
    </script>

</body>

</html>