<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.7/dist/tailwind.min.css">
    <title>Listas de Tareas</title>
</head>

<body class="bg-gray-100 flex items-center justify-center flex-col mc-auto ">
    <div class="flex mt-6 mr-auto ml-7">
        <?php
        $usuario = $_SESSION['user'];
        ?>
    </div>

    <?php
    $TaskController = new TaskController();
    $allTasks = $TaskController->tasksList_ViewAction();
    ?>

    <div class="mr-auto mt-4 ml-4">
        <a href="tasksList_View" class="bg-blue-300 text-white px-4 py-2 rounded hover:bg-blue-500">
            Tablón de tareas
        </a>
    </div>

    <div class="text-6xl font-bold text-black mb-8 mt-10 text-center">LISTAS DE TAREAS</div>

    <!-- Tabla de Tareas Pendientes -->
    <div class="mb-8">
        <h2 class="text-3xl font-semibold mb-4">Tareas Pendientes</h2>
        <table class="w-full border-collapse border border-blue-200">
            <?php
            $filteredTaskType = isset($_GET["filteredTaskType"]) ? $_GET["filteredTaskType"] : null;


            if (!empty($filteredTasks)) :
                foreach ($filteredTasks as $task) :
                    if ($filteredTaskType === null || $task['taskType'] === $filteredTaskType) :
            ?>
                        <tr>
                            <td class="text-center"><?php echo $task['taskName']; ?></td>
                        </tr>
            <?php
                    endif;
                endforeach;
            else :
                echo "<tr><td class='text-center'>No hay tareas pendientes</td></tr>";
            endif;
            ?>
        </table>
    </div>

   

    <script>
        function filterByTaskType() {
            let filteredTaskType = document.getElementById("filteredTaskType").value;

            if (filteredTaskType !== "--") {
                window.location.href = "?filteredTaskType=" + filteredTaskType;
            } else {
                // Puedes manejar aquí la lógica si no se proporciona un tipo de tarea
                alert("Para filtrar debes introducir algún dato!");
            }
        }
    </script>
</body>

</html>