<?php

enum TaskType: string {
    case FrontEnd = 'FrontEnd';
    case BackEnd = 'BackEnd';
    case DataScience = 'DataScience';
}

enum TaskStatus: string {
    case Pending = 'Pendiente';
    case Finished = 'Finalizada';
    case InProcess = 'En Ejecucion';
}

?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Tarea</title>
</head>
<body>
    <h1>Actualizar Tarea</h1>
    <?php if ($task): ?>
        <form action="updateTask" method="post">
            <label for="taskName">Nombre de la Tarea:</label>
            <input type="text" name="taskName" value="<?= htmlspecialchars($task['taskName']); ?>">

            <label for="taskType">Tipo de Tarea:</label>
            <select name="taskType">
                <option value="FrontEnd" <?php echo $task['taskType'] == 'FrontEnd' ? 'selected' : ''; ?>>FrontEnd</option>
                <option value="BackEnd" <?php echo $task['taskType'] == 'BackEnd' ? 'selected' : ''; ?>>BackEnd</option>
                <option value="DataScience" <?php echo $task['taskType'] == 'DataScience' ? 'selected' : ''; ?>>DataScience</option>
            </select>

            <label for="taskStatus">Estado de la Tarea:</label>
            <select name="taskStatus">
                <option value="Pendiente" <?php echo $task['taskStatus'] == 'Pendiente' ? 'selected' : ''; ?>>Pending</option>
                <option value="Finalizada" <?php echo $task['taskStatus'] == 'Finalizada' ? 'selected' : ''; ?>>Finished</option>
                <option value="En Proceso" <?php echo $task['taskStatus'] == 'En Proceso' ? 'selected' : ''; ?>>InProgress</option>
            </select>

            <button type="submit">Guardar Cambios</button>
        </form>
    <?php else: ?>
        <p>Tarea no encontrada.</p>
    <?php endif; ?>
</body>
</html>

