<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Welcome to ToDoList</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">

</head>
<style>
    .invalidUser {
        color: red;
        text-align: center;
        font-size: 1.3em;
    }
</style>

<body class="bg-blue-200 dark:bg-gray-900 flex items-center justify-center">
    <div class="bg-white mt-10 rounded-lg shadow-md flex flex-col justify-center p-6 py-24 lg:px-36 mx-auto border-5">
        <div class="sm:mx-auto sm:w-full sm:max-w-sm">
            <h2 class="mt-10 text-center text-4xl font-bold leading-9 tracking-tight text-gray-900">GESTOR DE TAREAS</h2>
        </div>
        <br><br>

        <div class="text-xl">
            <a href="loginUsersForm_View" class="flex w-full justify-center rounded-sm bg-gray-300 py-2 font-semibold leading-6 hover:bg-blue-300 mb-7">Inicio de sesión</a>
            <a href="createUsersForm_View" class="flex w-full justify-center rounded-sm bg-gray-300 py-2 font-semibold leading-6 hover:bg-blue-300 mt-5">Registro</a>
        </div>
    </div>
    <div>
        <?php
        if (isset($_GET['createdUser'])) {
            echo "<p class='invalidUser'>Se ha creado el usuario correctamente!</p>";
        }
        ?>
    </div>
</body>

</html>