<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.7/dist/tailwind.min.css">
    <title>Espacio del Usuario</title>

</head>
<body>
    <h1>Espacio del Usuario</h1>

    <table>
        <tr>
            <td colspan="2">
            <a href="/updateUserProfile> <input type=" button" value=">Actualizar Perfil"></a>

            </td>
        </tr>
        <tr>
            <td colspan="2">
               <a href="deleteUser" =<?php echo $task['taskId']?>" onclick="return confirmDelete(<?php echo $task['taskId']?>);">
                <input type='button' name='del' id='del' value='Borrar'></a>

            </td>
        </tr>
    </table>
    <script>
    function confirmDelete(id) {
    return confirm("¿Estás seguro de que deseas eliminar el perfil?");}
</script>
</body>
</html>