<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<?php
require_once "../../../controllers/class/ToDoController.php";
require_once "../../../controllers/class/tareaController.php";
require_once "../../../controllers/class/UsuarioController.php";

$tarea1 = new Task( "Agregar color fondo", tipoTarea::FRONTEND, "2021-01-01", "2021-01-10", estadoTarea::PENDIENTE); 
$tarea2 = new Task( "Crear funcion sumar", tipoTarea::BACKEND, "2022-11-04", "2022-12-15", estadoTarea::EN_EJECUCION); 

$usuario1 = new User("ribol", "jk2389m");
$usuario2 = new User("rasbil", "nns42l");

$toDo = new ToDo();
$toDo->createTarea($tarea2,$usuario1);

var_dump($toDo->getTareas());


?>
<body>
    
</body>
</html>